#![no_main]
sp1_zkvm::entrypoint!(main);

use serde::{Deserialize, Serialize};

/// The public context, defining the Constitution rules for the AI.
#[derive(Serialize, Deserialize)]
struct ConstitutionConfig {
    pub max_spend_limit: u64,
    pub whitelisted_address: Vec<u8>, 
}

/// The private intent generated by the AI Orchestrator.
#[derive(Serialize, Deserialize)]
struct AgentIntent {
    pub intent_amount: u64,
    pub target_address: Vec<u8>,
    pub asset_id: u32,
    pub signature: Vec<u8>, 
}

pub fn main() {
    // 1. Read the public inputs (The Constitution / Rules)
    let config = sp1_zkvm::io::read::<ConstitutionConfig>();

    // 2. Read the private inputs (The AI's intended transaction)
    let intent = sp1_zkvm::io::read::<AgentIntent>();

    // 3. Rule Execution: Max Spend Constraint
    if intent.intent_amount > config.max_spend_limit {
        panic!("CONSTITUTION VIOLATION: Intent amount exceeds max_spend_limit");
    }

    // 4. Rule Execution: Whitelist Constraint 
    // Agent can only interact with its designated safe addresses
    if intent.target_address != config.whitelisted_address {
        panic!("CONSTITUTION VIOLATION: Target address is not whitelisted");
    }

    // 5. Commit the sanitized, proven public outputs to the journal.
    // We only commit the intent data that is safe to expose on 0G Chain.
    // The private logic or hidden thresholds remain completely secure inside the ZK proof.
    sp1_zkvm::io::commit(&intent.intent_amount);
    sp1_zkvm::io::commit(&intent.target_address);
    sp1_zkvm::io::commit(&intent.asset_id);
}
