// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IZKVerifier
 * @dev Interface for Zero Knowledge Proof verifier contracts.
 *      Designed to match the Groth16 verifier generated by snarkjs.
 */
interface IZKVerifier {
    /**
     * @dev Verifies a Groth16 proof against the provided public inputs.
     * @param _pA  Proof point A  [2 elements]
     * @param _pB  Proof point B  [2][2 elements]
     * @param _pC  Proof point C  [2 elements]
     * @param _pubSignals Public signals array (intentAmount, targetAddress, assetId, valid)
     * @return bool True if the proof is valid
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}
