/**
 * Sovereign Agent Prover — snarkjs Groth16
 * -----------------------------------------
 * Replaces the SP1 host prover script (script/src/main.rs).
 *
 * This script:
 * 1. Reads the WASM circuit + proving key from the build/ directory
 * 2. Constructs circuit inputs (Constitution + Intent)
 * 3. Generates a Groth16 proof
 * 4. Verifies the proof locally
 * 5. Exports the proof in a format ready for on-chain submission
 */

import * as snarkjs from "snarkjs";
import * as path from "path";
import * as fs from "fs";
import {
    ConstitutionConfig,
    AgentIntent,
    CircuitInput,
    ProofPackage,
    addressToBigInt,
    bigIntToAddress,
} from "./types";

// Paths to the compiled circuit artifacts (generated by `npm run build:circuit` + `npm run setup`)
const BUILD_DIR = path.join(__dirname, "..", "build");
const WASM_PATH = path.join(BUILD_DIR, "constitution_js", "constitution.wasm");
const ZKEY_PATH = path.join(BUILD_DIR, "constitution_final.zkey");
const VKEY_PATH = path.join(BUILD_DIR, "verification_key.json");

/**
 * Generate a Groth16 proof that an agent's intent complies with its Constitution.
 */
async function generateProof(
    config: ConstitutionConfig,
    intent: AgentIntent
): Promise<ProofPackage> {
    // Build the circuit input object
    // snarkjs expects all values as decimal strings
    const circuitInput: CircuitInput = {
        intentAmount: intent.intentAmount.toString(),
        targetAddress: intent.targetAddress.toString(),
        assetId: intent.assetId.toString(),
        maxSpendLimit: config.maxSpendLimit.toString(),
        whitelistedAddress: config.whitelistedAddress.toString(),
    };

    console.log("🔧 Circuit inputs prepared:");
    console.log(`   intentAmount     = ${circuitInput.intentAmount}`);
    console.log(`   targetAddress    = ${bigIntToAddress(intent.targetAddress)}`);
    console.log(`   assetId          = ${circuitInput.assetId}`);
    console.log(`   maxSpendLimit    = [PRIVATE]`);
    console.log(`   whitelistedAddr  = [PRIVATE]\n`);

    // Generate the witness and the proof
    console.log("⏳ Generating Groth16 proof...\n");
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        circuitInput,
        WASM_PATH,
        ZKEY_PATH
    );

    return { proof, publicSignals };
}

/**
 * Verify a proof locally using the verification key.
 */
async function verifyProofLocally(proofPkg: ProofPackage): Promise<boolean> {
    const vkeyJson = JSON.parse(fs.readFileSync(VKEY_PATH, "utf-8"));
    return snarkjs.groth16.verify(vkeyJson, proofPkg.publicSignals, proofPkg.proof);
}

/**
 * Format a proof for on-chain Solidity verifier submission.
 * Returns the (a, b, c, input) arrays expected by the Groth16Verifier contract.
 */
function formatForSolidity(proofPkg: ProofPackage) {
    const { proof, publicSignals } = proofPkg;
    return {
        a: [proof.pi_a[0], proof.pi_a[1]],
        b: [
            [proof.pi_b[0][1], proof.pi_b[0][0]], // Note: snarkjs reverses b coords for Solidity
            [proof.pi_b[1][1], proof.pi_b[1][0]],
        ],
        c: [proof.pi_c[0], proof.pi_c[1]],
        input: publicSignals,
    };
}

// ============================================================
// MAIN — Demo flow matching the original SP1 prover script
// ============================================================
async function main() {
    console.log("==================================================");
    console.log("🔐 SOVEREIGN AGENT ZK PROVER — snarkjs Groth16");
    console.log("==================================================\n");

    // Check that build artifacts exist
    if (!fs.existsSync(WASM_PATH) || !fs.existsSync(ZKEY_PATH)) {
        console.error("❌ Build artifacts not found. Run the following first:");
        console.error("   npm run build:circuit");
        console.error("   npm run setup");
        process.exit(1);
    }

    // 1. Define the Constitution constraints (same values as the SP1 demo)
    //    Max 1000 tokens, specific whitelisted address
    const whitelistedAddr = "0xDEADBEEF000000000000000000000000000000000000";
    const config: ConstitutionConfig = {
        maxSpendLimit: 1000n,
        whitelistedAddress: addressToBigInt("0xDEADBEEF00000000000000000000000000000000"),
    };

    // 2. Define the AI intent (800 tokens to the whitelisted address)
    const intent: AgentIntent = {
        intentAmount: 800n, // Valid: 800 <= 1000
        targetAddress: config.whitelistedAddress, // Valid: matches whitelist
        assetId: 1n,
    };

    // 3. Generate proof
    console.log("Starting snarkjs Groth16 Prover for Sovereign Agent intent...\n");
    const proofPkg = await generateProof(config, intent);
    console.log("✅ Proof generated successfully! The Agent followed the Constitution.\n");

    // 4. Decode public signals (these are what the chain sees)
    console.log("📋 Public Signals (on-chain visible):");
    console.log(`   intentAmount   = ${proofPkg.publicSignals[0]}`);
    console.log(`   targetAddress  = ${bigIntToAddress(BigInt(proofPkg.publicSignals[1]))}`);
    console.log(`   assetId        = ${proofPkg.publicSignals[2]}`);
    console.log(`   valid          = ${proofPkg.publicSignals[3]}\n`);

    // 5. Verify locally
    console.log("🔍 Verifying proof locally...");
    const isValid = await verifyProofLocally(proofPkg);
    if (isValid) {
        console.log("✅ Verification successful.\n");
    } else {
        console.error("❌ Verification FAILED.");
        process.exit(1);
    }

    // 6. Show Solidity calldata format
    const solidityData = formatForSolidity(proofPkg);
    console.log("📦 Solidity calldata (for on-chain verification):");
    console.log(JSON.stringify(solidityData, null, 2));

    // 7. Export proof to file for the AI orchestrator to pick up
    const outputPath = path.join(BUILD_DIR, "latest_proof.json");
    fs.writeFileSync(outputPath, JSON.stringify(proofPkg, null, 2));
    console.log(`\n💾 Proof saved to ${outputPath}`);
}

main().catch((err) => {
    console.error("Fatal error:", err);
    process.exit(1);
});

export { generateProof, verifyProofLocally, formatForSolidity };
