/**
 * Shared types for the ZK Engine
 * These mirror the structures from the original SP1 guest program.
 */

/** The private Constitution rules governing the AI agent */
export interface ConstitutionConfig {
    /** Maximum amount the agent can spend in a single intent (u64) */
    maxSpendLimit: bigint;
    /** The only EVM address the agent may transact with (20 bytes → bigint) */
    whitelistedAddress: bigint;
}

/** The intent generated by the AI Orchestrator */
export interface AgentIntent {
    /** How much the agent wants to spend */
    intentAmount: bigint;
    /** Target EVM address the agent wants to interact with */
    targetAddress: bigint;
    /** Asset identifier */
    assetId: bigint;
}

/**
 * The full circuit input object fed to snarkjs witness generation.
 * Public signals: intentAmount, targetAddress, assetId
 * Private signals: maxSpendLimit, whitelistedAddress
 */
export interface CircuitInput {
    intentAmount: string;
    targetAddress: string;
    assetId: string;
    maxSpendLimit: string;
    whitelistedAddress: string;
}

/** Groth16 proof structure as returned by snarkjs */
export interface Groth16Proof {
    pi_a: [string, string, string];
    pi_b: [[string, string], [string, string], [string, string]];
    pi_c: [string, string, string];
    protocol: string;
    curve: string;
}

/** Full proof package (proof + public signals) */
export interface ProofPackage {
    proof: Groth16Proof;
    publicSignals: string[];
}

/**
 * Convert a hex EVM address string to a BigInt.
 * Example: "0xDEADBEEF..." → 1272846955n...
 */
export function addressToBigInt(address: string): bigint {
    if (!address.startsWith("0x")) {
        address = "0x" + address;
    }
    return BigInt(address);
}

/**
 * Convert a BigInt back to a 0x-prefixed hex address string (40 hex chars).
 */
export function bigIntToAddress(value: bigint): string {
    return "0x" + value.toString(16).padStart(40, "0");
}
